name: 'W-Extend-2'

on:
  #push:
  schedule:
    # UTC (国内 UTC+8)
     - cron: '20 20 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    #runs-on: macos-12

    steps:
        - name: 'Checkout codes'
          uses: actions/checkout@v2
          
        - name: 'Update Chrome'           
          run: |
            brew reinstall --cask google-chrome

        - name: 'Install requirements'
          run: |
            pip3 install urllib3
            pip3 install requests
            pip3 install helium
            pip3 install datefinder
            pip3 install undetected-chromedriver
            pip3 uninstall selenium -y
            pip3 install selenium==4.2.0
            
     #   - name: 'Renew'
       #   env:
       #     USER_ID_W_2: ${{ secrets.USER_ID_W_2 }}
       #     PASS_WD_W_2: ${{ secrets.PASS_WD_W_2 }}
       #     BARK_KEY: ${{ secrets.BARK_KEY }}
        #    TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        #    TG_USER_ID: ${{ secrets.TG_USER_ID }}

      #    run: |
      #      python3 VPS/main-w-2.py
         
        - name: 'Convert to json'
          run: |
             ##akamino 交给你了
             ##已知：在 w-2.txt 中
             ##有🎉 Your VPS has been renewed until August 15, 2022
             ##请 让变量 $extend  =等于日期
             ##例如 
             extend="2022.08.15"
             wget -O api/w-2.json  --no-check-certificate https://speedcloud.cf/api/v3/file/source/61195/example.json?sign=QoJqHGiCVP2xkf1KjoYqXKaiSrL7wc_gaNSfcHYMhdA%3D%3A0
             echo "-Downloaded json"
             sed -i 's/'"name"'/'"w-2"'/g' api/w-2.json
             sed -i 's/'"extend"'/'"$extend"'/g' api/w-2.json

        - name: 'Delete Files'
          run: |
             rm -rf audio.mp3
             rm -rf w-2.txt
             rm -rf capture.png

        - name: 'Commit Files'
          run: |
             git config --local user.email "action@github.com"
             git config --local user.name "GitHub Action"
             git add .
             git diff --quiet && git diff --staged --quiet || git commit -am "$(date '+%Y.%m.%d %H:%M:%S') H-1"
             echo ::set-output name=status::success
             
        - name: 'GitHub Push'
          uses: ad-m/github-push-action@v0.6.0
          with:
             github_token: ${{ secrets.GITHUB_TOKEN }}
             branch: ${{ github.ref }}

