
name: 'H-Extend-12'

on:
  #push:
  schedule:
    # UTC (国内 UTC+8)
     - cron: '40 20 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    #runs-on: macos-latest
    runs-on: macos-12

    steps:
        - name: 'Checkout codes'
          uses: actions/checkout@v2
          
        - name: 'Update Chrome'           
          run: |
            brew reinstall --cask google-chrome
        - name: 'Install requirements'
          run: |
            pip3 install -r VPS/requirements.txt
            pip3 install undetected-chromedriver
            yes | pip3 uninstall selenium
            pip3 install selenium==4.2.0
            
        - name: 'Renew'
          env:
            USER_ID_H_12: ${{ secrets.USER_ID_H_12 }}
            PASS_WD_H_12: ${{ secrets.PASS_WD_H_12 }}
            BARK_KEY: ${{ secrets.BARK_KEY }}
            TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
            TG_USER_ID: ${{ secrets.TG_USER_ID }}

          run: |
            python3 VPS/main-h-12.py
